import type { DB } from "./types";

export const ONBOARDING_ITEMS = [
  "Logo received",
  "Brand assets received",
  "Images received",
  "Videos received",
  "Website content received",
  "Contact information received",
  "Social media links received",
  "Domain access received",
  "Hosting access received",
  "API credentials received",
  "CMS requirements confirmed",
  "Project scope confirmed",
];

export const WORKFLOW = [
  "LEAD", "DISCOVERY", "SCOPE", "PRICING", "QUOTE", "PROPOSAL",
  "NEGOTIATION", "AGREEMENT", "ADVANCE", "ONBOARDING", "DESIGN",
  "DEVELOPMENT", "QA", "FINAL PAYMENT", "LAUNCH", "MAINTENANCE",
];

export const seedDB: DB = {
  leads: [
    {
      id: "lead_abc", company: "ABC Properties", industry: "Real Estate",
      website: "abcproperties.in", location: "Pune", companySize: "11-50",
      contactName: "Rohit Sharma", phone: "+91 98220 00001", whatsapp: "+91 98220 00001",
      email: "rohit@abcproperties.in", role: "Director",
      service: "Business Website", currentWebsite: "old abc site, slow, not mobile friendly",
      problem: "No leads from website, looks outdated", outcome: "More site-visit bookings + credibility",
      budget: 45000, timeline: "4 weeks", references: "sobha.com, lodha",
      source: "Instagram", dateAdded: "2026-09-10", score: 82, stage: "proposal",
      nextFollowUp: "2026-09-23", notes: "Hot lead. Wants premium look.",
      currentSituation: "Basic WordPress site, slow, no enquiry tracking.",
      problems: "Slow load, no mobile UX, no WhatsApp, weak SEO.",
      opportunities: "Project pages, WhatsApp CTA, SEO, analytics.",
      recommended: "ARKRIA GROW — 6 page site + CMS + lead system",
      features: ["Responsive website", "CMS", "WhatsApp integration", "Lead forms", "SEO", "Analytics"],
      estLow: 35000, estHigh: 55000, demo: true,
    },
    {
      id: "lead_snl", company: "Space N Living", industry: "Interiors",
      website: "spacenliving.com", instagram: "@spacenliving", location: "Mumbai",
      companySize: "2-10", contactName: "Priya Nair", phone: "+91 98111 22233",
      email: "hello@spacenliving.com", role: "Founder",
      service: "Premium Interactive Website", problem: "Portfolio doesn't reflect premium work",
      outcome: "High-end brand + Instagram-to-enquiry funnel",
      budget: 90000, timeline: "6 weeks", source: "Referral",
      dateAdded: "2026-09-14", score: 74, stage: "discovery",
      nextFollowUp: "2026-09-22", notes: "Loves animations. Shared 3 refs.",
      currentSituation: "Wix portfolio, generic template.",
      problems: "Template look, poor imagery showcase, no case studies.",
      opportunities: "Editorial portfolio, motion, project stories, enquiry flow.",
      recommended: "ARKRIA EXPERIENCE — immersive portfolio",
      features: ["Animation", "CMS", "SEO", "Analytics", "Lead forms"],
      estLow: 60000, estHigh: 110000, demo: true,
    },
    {
      id: "lead_prop", company: "PropDost", industry: "PropTech",
      contactName: "Amit Verma", phone: "+91 99000 11223", email: "amit@propdost.in",
      service: "Web Application", problem: "Needs listing + CRM MVP",
      outcome: "Launch MVP in 8 weeks", budget: 250000, timeline: "8 weeks",
      source: "Website", dateAdded: "2026-09-16", score: 68, stage: "interested",
      nextFollowUp: "2026-09-24", location: "Bengaluru",
      currentSituation: "No product yet, Figma only.",
      problems: "No build partner, unclear scope.",
      opportunities: "MVP: listings, admin, WhatsApp, search.",
      recommended: "CUSTOM — scoped MVP phase 1",
      features: ["Dashboard", "CMS", "WhatsApp integration", "Analytics"],
      estLow: 180000, estHigh: 280000, demo: true,
    },
    {
      id: "lead_sam", company: "Samatva Group", industry: "Real Estate",
      contactName: "Kavya Reddy", phone: "+91 97654 32109", email: "kavya@samatva.in",
      service: "Corporate Website", source: "Cold outreach",
      dateAdded: "2026-09-18", score: 55, stage: "contacted",
      nextFollowUp: "2026-09-21", location: "Hyderabad",
      problem: "Rebrand needs new site", outcome: "Investor-ready corporate presence",
      budget: 50000, timeline: "5 weeks",
      currentSituation: "Old static site from 2019.",
      problems: "Outdated brand, no CMS.",
      opportunities: "Rebrand + CMS + newsroom.",
      recommended: "ARKRIA GROW",
      features: ["Responsive website", "CMS", "SEO"],
      estLow: 30000, estHigh: 60000, demo: true,
    },
    {
      id: "lead_tpp", company: "The Property Point", industry: "Brokerage",
      contactName: "Sahil Khan", phone: "+91 98888 77766",
      service: "Landing Page", source: "WhatsApp",
      dateAdded: "2026-09-19", score: 48, stage: "new",
      nextFollowUp: "2026-09-22", location: "Pune",
      problem: "New campaign needs landing page", outcome: "Campaign leads",
      budget: 18000, timeline: "2 weeks",
      currentSituation: "No landing infra.",
      problems: "Running ads to homepage.",
      opportunities: "Dedicated landing + lead form + tracking.",
      recommended: "ARKRIA START",
      features: ["Responsive website", "Lead forms", "WhatsApp integration", "Analytics"],
      estLow: 15000, estHigh: 25000, demo: true,
    },
  ],
  clients: [
    {
      id: "cl_abc", company: "ABC Properties", industry: "Real Estate",
      contactName: "Rohit Sharma", email: "rohit@abcproperties.in",
      phone: "+91 98220 00001", location: "Pune", website: "abcproperties.in",
      notes: "Prefers WhatsApp. Decision maker.",
      onboarding: { "Logo received": true, "Brand assets received": true, "Images received": true, "Videos received": false, "Website content received": true, "Contact information received": true, "Social media links received": true, "Domain access received": true, "Hosting access received": false, "API credentials received": false, "CMS requirements confirmed": true, "Project scope confirmed": true },
      dateAdded: "2026-08-02", demo: true,
    },
    {
      id: "cl_snl", company: "Space N Living", industry: "Interiors",
      contactName: "Priya Nair", email: "hello@spacenliving.com",
      phone: "+91 98111 22233", location: "Mumbai",
      notes: "Very design-sensitive.", onboarding: {},
      dateAdded: "2026-08-20", demo: true,
    },
  ],
  services: [
    { id: "s1", name: "Business Website", category: "Websites", description: "5-8 page credibility + lead site", basePrice: 38000, internalCost: 20000, hours: 60, complexity: "Medium", clientFacing: "Custom-designed, mobile-first website with lead capture and SEO setup.", active: true },
    { id: "s2", name: "Landing Page", category: "Websites", description: "High-converting campaign page", basePrice: 16000, internalCost: 8000, hours: 24, complexity: "Low", clientFacing: "Focused landing page engineered for conversions.", active: true },
    { id: "s3", name: "Premium Interactive Website", category: "Websites", description: "GSAP / motion / editorial", basePrice: 85000, internalCost: 45000, hours: 140, complexity: "Expert", clientFacing: "Award-level interactive experience with advanced motion.", active: true },
    { id: "s4", name: "Custom E-commerce", category: "E-commerce", description: "Catalog + payments + shipping", basePrice: 95000, internalCost: 55000, hours: 160, complexity: "High", clientFacing: "Full store with payments, shipping and inventory.", active: true },
    { id: "s5", name: "SaaS / Dashboard", category: "Web Applications", description: "Auth, roles, dashboards, API", basePrice: 180000, internalCost: 110000, hours: 300, complexity: "Expert", clientFacing: "Scalable web app with dashboards and integrations.", active: true },
    { id: "s6", name: "Cross-platform Mobile App", category: "Mobile Apps", description: "Customer + admin app", basePrice: 220000, internalCost: 140000, hours: 380, complexity: "Expert", clientFacing: "iOS + Android app from one codebase.", active: true },
    { id: "s7", name: "AI Chatbot", category: "AI", description: "Support / lead bot on your data", basePrice: 60000, internalCost: 32000, hours: 90, complexity: "High", clientFacing: "AI assistant trained on your business.", active: true },
    { id: "s8", name: "SEO + Performance", category: "Ongoing", description: "Core vitals, metadata, speed", basePrice: 12000, internalCost: 5000, hours: 16, complexity: "Medium", clientFacing: "Faster site, better rankings.", active: true },
  ],
  packages: [
    { id: "p1", name: "ARKRIA START", tagline: "Basic professional presence", low: 15000, high: 30000, best: false, features: ["1–4 pages", "Responsive design", "Custom UI", "Contact form", "WhatsApp", "Basic SEO", "Deployment", "Basic animations"] },
    { id: "p2", name: "ARKRIA GROW", tagline: "Credibility + lead generation", low: 30000, high: 60000, best: true, features: ["5–8 pages", "Custom UI/UX", "CMS", "Lead forms", "WhatsApp", "Analytics", "SEO setup", "Animations", "Performance", "Deployment"] },
    { id: "p3", name: "ARKRIA EXPERIENCE", tagline: "Premium digital experience", low: 60000, high: 150000, best: false, features: ["Highly custom UI", "Advanced animations", "GSAP + scroll", "Advanced CMS", "API integrations", "Interactive sections", "3D where required", "Advanced forms", "Performance", "Analytics + SEO"] },
    { id: "p4", name: "CUSTOM", tagline: "Apps, SaaS, AI, platforms", low: 150000, high: null, best: false, features: ["Scoping workshop", "Architecture", "Custom design", "Backend + API", "Integrations", "QA + launch", "Docs + handover"] },
  ],
  quotes: [
    {
      id: "q1", no: "ARK-2026-014", clientId: "cl_abc", clientName: "ABC Properties",
      items: [
        { id: "qi1", label: "Website Strategy & UI/UX", qty: 1, price: 8000 },
        { id: "qi2", label: "Website Development (6 pages)", qty: 1, price: 18000 },
        { id: "qi3", label: "CMS Integration", qty: 1, price: 5000 },
        { id: "qi4", label: "Lead Generation System", qty: 1, price: 3000 },
        { id: "qi5", label: "SEO Setup", qty: 1, price: 2000 },
        { id: "qi6", label: "Deployment", qty: 1, price: 2000 },
      ],
      discount: 3000, taxPct: 0, status: "sent",
      created: "2026-09-12", validUntil: "2026-09-26",
      notes: "50% advance, 30% on development milestone, 20% on launch.",
    },
  ],
  proposals: [
    {
      id: "pr1", clientName: "ABC Properties", clientId: "cl_abc", title: "Growth Website + Lead Engine",
      understanding: "ABC's current site is slow, not mobile-first, and generates almost no tracked enquiries.",
      opportunity: "A fast, premium site with project pages, WhatsApp CTAs and analytics can lift site-visit bookings.",
      approach: ["Discover", "Direction", "Design", "Build", "Launch"],
      solution: "6-page GROW build: Home, Projects, Project detail (CMS), About, Contact + blog-ready CMS.",
      sitemap: ["Home", "Projects", "Project Detail", "About", "Contact", "Blog (CMS)"],
      designDirection: "Editorial, warm neutrals, large imagery, subtle motion. Refs: Sobha, Lodha.",
      deliverables: ["Custom UI/UX", "Responsive build", "CMS", "Lead forms + WhatsApp", "SEO setup", "Analytics"],
      timeline: "Week 1 Discovery, Week 2 UI, Week 3 Build, Week 4 QA + Launch",
      investment: 35000, paymentPlan: [{ label: "Project commencement", pct: 50 }, { label: "Development milestone", pct: 30 }, { label: "Final approval", pct: 20 }],
      terms: "2 revision rounds per stage. Content provided by client. Hosting billed separately.",
      status: "sent", created: "2026-09-13",
    },
  ],
  projects: [
    {
      id: "pj1", name: "ABC Properties — Growth Website", clientId: "cl_abc",
      clientName: "ABC Properties", value: 35000, start: "2026-09-15",
      deadline: "2026-10-12", manager: "Krish", status: "development",
      progress: 55, notes: "Homepage approved. Building CMS now.", demo: true,
      tasks: [
        { id: "t1", title: "Discovery + sitemap locked", done: true },
        { id: "t2", title: "Homepage UI approved", done: true },
        { id: "t3", title: "Inner pages UI", done: false },
        { id: "t4", title: "CMS + lead forms", done: false },
        { id: "t5", title: "QA + launch", done: false },
      ],
      milestones: [
        { id: "m1", name: "Design approval", deadline: "2026-09-24", status: "done", payment: 17500, deliverables: "Homepage + style" },
        { id: "m2", name: "Development milestone", deadline: "2026-10-05", status: "in-progress", payment: 10500, deliverables: "Full site on staging" },
        { id: "m3", name: "Launch", deadline: "2026-10-12", status: "pending", payment: 7000, deliverables: "Production + analytics" },
      ],
    },
    {
      id: "pj2", name: "Space N Living — Portfolio", clientId: "cl_snl",
      clientName: "Space N Living", value: 75000, start: "2026-09-20",
      deadline: "2026-11-02", manager: "Krish", status: "design",
      progress: 25, notes: "Moodboards in review.", demo: true,
      tasks: [
        { id: "t1", title: "Moodboard + direction", done: true },
        { id: "t2", title: "Homepage concept", done: false },
        { id: "t3", title: "Case study template", done: false },
      ],
      milestones: [
        { id: "m1", name: "Design approval", deadline: "2026-10-04", status: "in-progress", payment: 37500, deliverables: "Full UI" },
        { id: "m2", name: "Launch", deadline: "2026-11-02", status: "pending", payment: 37500, deliverables: "Live site" },
      ],
    },
  ],
  payments: [
    { id: "pay1", projectId: "pj1", clientName: "ABC Properties", label: "Advance 50%", amount: 17500, due: "2026-09-15", paidDate: "2026-09-15", status: "paid", method: "UPI", txn: "UPI98231" },
    { id: "pay2", projectId: "pj1", clientName: "ABC Properties", label: "Milestone 30%", amount: 10500, due: "2026-10-05", status: "pending" },
    { id: "pay3", projectId: "pj1", clientName: "ABC Properties", label: "Final 20%", amount: 7000, due: "2026-10-12", status: "pending" },
    { id: "pay4", projectId: "pj2", clientName: "Space N Living", label: "Advance 50%", amount: 37500, due: "2026-09-25", status: "overdue" },
  ],
  scopes: [
    { id: "sc1", projectId: "pj1", projectName: "ABC Properties — Growth Website", feature: "Blog + CMS extra templates", description: "Client asked for 3 extra CMS templates beyond agreed 1.", hours: 10, cost: 8000, timelineImpact: "+3 days", status: "quoted", created: "2026-09-18" },
  ],
  subs: [
    { id: "sub1", clientId: "cl_abc", clientName: "ABC Properties", plan: "STANDARD", monthly: 5000, renewal: "2026-10-15", includedHours: 5, usedHours: 2, status: "active" },
  ],
  templates: [
    { id: "tm1", category: "WhatsApp", title: "First Contact", body: "Hi {{name}}, this is Krish from Arkria — we build premium websites for real-estate brands. Saw {{company}} — quick idea to lift enquiries. Open to a 15-min call?" },
    { id: "tm2", category: "Follow-up", title: "Follow-up 1 (2 days)", body: "Hi {{name}}, just bumping the proposal for {{company}} ({{amount}}). Happy to walk through scope on a quick call. — Krish, Arkria" },
    { id: "tm3", category: "Email", title: "Proposal Sent", body: "Subject: Arkria × {{company}} — proposal inside\n\nHi {{name}},\n\nAttached is the proposal: scope, timeline and investment ({{amount}}). Valid till {{date}}.\n\nNext step: 20-min review call?\n\n— Krish" },
    { id: "tm4", category: "Payment", title: "Payment Reminder", body: "Hi {{name}}, friendly reminder: {{label}} of {{amount}} was due {{date}}. UPI: {{upi}}. Reply once done and I'll confirm instantly. — Arkria" },
    { id: "tm5", category: "Project", title: "Project Started", body: "Hi {{name}}, advance received — your project is now active. Onboarding checklist: logo, content, accesses. Let's launch strong. — Arkria" },
    { id: "tm6", category: "Maintenance", title: "Maintenance Offer", body: "Hi {{name}}, your site is live. To keep it fast + safe, our CARE plans start ₹2,500/mo. Want me to activate STANDARD for {{company}}?" },
  ],
  comms: [
    { id: "c1", date: "2026-09-16", clientName: "ABC Properties", channel: "WhatsApp", summary: "Sent proposal walkthrough. Client asked about CMS training — confirmed included." },
    { id: "c2", date: "2026-09-18", clientName: "Space N Living", channel: "Call", summary: "Loves direction B. Wants motion refs before homepage concept." },
  ],
  settings: { studio: "Arkria", owner: "Krish", email: "hello@arkria.in", phone: "+91 90000 00000", upi: "arkria@upi" },
};
